cleanup

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,52 +5,45 @@
 
 set -e -u -x
 echo "This is the chadow install script."
-if [[ ! -z "FULL_TESTING" ]] || [[ $FULL_TESTING -eq 1 ]]; then
-    # Turn off -u because this is not our script
-    set +e +u
-    source ~/.venvburrito/bin/virtualenvwrapper.sh
-    set -e -u
-fi
-
-if [[ ! -z "$FULL_TESTING" ]]; then
-    set -x
-fi
-
 mkdir ~/.chadow
 touch ~/.chadow/config.json
 version="$(cat VERSION)"
 echo "{\"version\": \"$version\", \"libraryMapping\":{}}" > ~/.chadow/config.json
 
-if [[ ! -z "FULL_TESTING" ]] || [[ $FULL_TESTING -eq 1 ]]; then
-    # Turn off verbose since it is too noisy for lsvirtualenv.
-    set +x
-    chadow_existence="$(lsvirtualenv | grep chadow | wc -l)"
-    set -x
-    
-    echo "existence: $chadow_existence"
-    
-    if [[ "$chadow_existence" != 0 ]]; then
-        echo "A chadow virtualenv exists. Please completely uninstall chadow first."
-        exit 1
-    fi
-    
-    # Turn off error exit since, for some reason, this install script halts on
-    # mkvirtualenv with exit error on.
-    # Turn off verbose since virtualenv is noisy.
-    set +e +x +u
-    echo "Creating chadow virtualenv..."
-    mkvirtualenv chadow -p python3.7
-    echo "virtualenv created."
-    set -e
-    
-    # For some reason, without the next two echo statements, installation fails on
-    # Travis CI.
-    echo "Working on virtualenv..."
-    workon chadow
-    echo "Now on virtualenv. Turning verbose on again."
-    set -x -u
-    pip install -r requirements.txt
+# Turn off -u because this is not our script
+set +e +u
+source ~/.venvburrito/bin/virtualenvwrapper.sh
+set -e -u
+
+# Turn off verbose since it is too noisy for lsvirtualenv.
+set +x
+chadow_existence="$(lsvirtualenv | grep chadow | wc -l)"
+set -x
+
+echo "existence: $chadow_existence"
+
+if [[ "$chadow_existence" != 0 ]]; then
+    echo "A chadow virtualenv exists. Please completely uninstall chadow first."
+    exit 1
 fi
+
+# Turn off error exit since, for some reason, this install script halts on
+# mkvirtualenv with exit error on.
+# Turn off verbose since virtualenv is noisy.
+set +e +x +u
+echo "Creating chadow virtualenv..."
+mkvirtualenv chadow -p python3.7
+echo "virtualenv created."
+set -e
+
+# For some reason, without the next two echo statements, installation fails on
+# Travis CI.
+echo "Working on virtualenv..."
+workon chadow
+echo "Now on virtualenv. Turning verbose on again."
+set -x -u
+pip install -r requirements.txt
+
 set +x +e +u
 cp chadow.py ~/.chadow
 echo "Done installing. Do 'workon chadow' to start using chadow."
